-- 0037_numeros_afiliado_y_pausa.sql
-- Número de afiliado, número de usuario y pausa de cuota (decisiones de Sergio,
-- 01/08/2026).
--
--  1. NÚMERO DE USUARIO: entero para TODA persona registrada. Hoy solo existe
--     el uuid de auth.users, que no sirve para decir "soy el usuario 214" por
--     teléfono. No sustituye al uuid: convive con él.
--
--  2. NÚMERO DE AFILIADO: entero, correlativo y SIN HUECOS. Va en `profiles`,
--     no en `members`, y esto es deliberado: alguien puede darse de baja y
--     volver, lo que genera una segunda fila en `members`; si el número
--     colgara de ahí, al reingresar recibiría uno nuevo. Colgando de la
--     persona, quien vuelve recupera el suyo y ningún número se reutiliza
--     jamás para otra persona. El libro de afiliados tiene peso legal (Ley de
--     Partidos, LO 8/2007): un hueco o un número reciclado son un problema de
--     trazabilidad, no una minucia estética.
--
--     Se asigna en el PRIMER COBRO EFECTIVO (cuando la afiliación pasa a
--     `active`), no al rellenar el formulario: si se asignara al registrarse,
--     cada alta abandonada quemaría un número y el libro quedaría con huecos
--     que nadie sabría explicar.
--
--     El relleno con ceros (00001) es PRESENTACIÓN y se hace en la interfaz.
--     Guardar '00042' impediría ordenar y calcular el siguiente.
--
--  3. PAUSA DE CUOTA: nuevo estado `paused` en `members`. Decisión de Sergio:
--     durante la pausa se CONSERVAN los derechos de afiliado (es una pausa
--     acordada, no un impago), así que hay que tocar las tres funciones/vistas
--     que hoy exigen `status = 'active'` — si no, pausar quitaría el voto en
--     silencio, que es justo lo contrario de lo decidido.

begin;

-- ============================================================================
-- 1. Número de usuario (todas las personas)
-- ============================================================================

alter table public.profiles
  add column user_number bigint generated by default as identity;

create unique index profiles_user_number_idx on public.profiles (user_number);

comment on column public.profiles.user_number is
  '0037: identificador corto y humano de CUALQUIER usuario (lo use o no la afiliación). No sustituye a id (uuid): es para buscar y para hablar con la persona ("usuario 214").';

-- ============================================================================
-- 2. Número de afiliado (solo quien llega a pagar)
-- ============================================================================

alter table public.profiles
  add column member_number int;

create unique index profiles_member_number_idx on public.profiles (member_number);

comment on column public.profiles.member_number is
  '0037: número del libro de afiliados. Correlativo, sin huecos, NUNCA reutilizado y se conserva entre baja y reingreso. Se asigna al primer cobro efectivo. Se muestra con ceros a la izquierda (presentación), aquí se guarda el entero.';

/**
 * Asigna el siguiente número libre. El bloqueo de transacción serializa las
 * asignaciones concurrentes: sin él, dos altas simultáneas leerían el mismo
 * max() y una fallaría por el índice único (o peor, con otra estrategia,
 * dejarían un hueco). A este volumen el coste es irrelevante y compra la
 * garantía de que el libro no tiene saltos.
 */
create or replace function public.asignar_numero_afiliado(p_user uuid)
returns int
language plpgsql security definer set search_path = public as $$
declare
  siguiente int;
  actual    int;
begin
  select member_number into actual from public.profiles where id = p_user;
  if actual is not null then
    return actual;  -- reingreso: conserva el suyo
  end if;

  perform pg_advisory_xact_lock(hashtext('numero_afiliado'));

  select coalesce(max(member_number), 0) + 1 into siguiente from public.profiles;
  update public.profiles set member_number = siguiente where id = p_user;
  return siguiente;
end;
$$;

comment on function public.asignar_numero_afiliado(uuid) is
  '0037: devuelve el número de afiliado del usuario, asignando el siguiente correlativo si aún no tiene. Idempotente: llamarla dos veces no consume dos números.';

/**
 * Dispara la asignación en cuanto una afiliación queda activa. Se hace en BD y
 * no en la app porque el alta puede venir por tres caminos (webhook de Stripe,
 * alta manual desde el panel, script de migración) y los tres deben numerar
 * igual. `paused` también numera: si alguien pausa antes de que el trigger
 * hubiera corrido, sigue siendo afiliado.
 */
create or replace function public.members_asignar_numero()
returns trigger
language plpgsql security definer set search_path = public as $$
begin
  if new.status in ('active', 'paused') then
    perform public.asignar_numero_afiliado(new.user_id);
  end if;
  return new;
end;
$$;

create trigger members_asignar_numero_trg
  after insert or update of status on public.members
  for each row execute function public.members_asignar_numero();

-- Numera a quien YA es afiliado, por orden de antigüedad real: el afiliado 1
-- debe ser el que lleva más tiempo, no el primero que devuelva la tabla.
do $$
declare
  fila record;
begin
  for fila in
    select distinct on (m.user_id) m.user_id, m.started_at, m.created_at
      from public.members m
      join public.profiles p on p.id = m.user_id
     where m.status in ('active', 'paused')
       and p.member_number is null
     order by m.user_id, m.started_at nulls last
  loop
    perform public.asignar_numero_afiliado(fila.user_id);
  end loop;
end $$;

-- ============================================================================
-- 3. Estado `paused` en members
-- ============================================================================

alter table public.members drop constraint members_status_check;
alter table public.members add constraint members_status_check
  check (status in ('active', 'past_due', 'paused', 'canceled'));

comment on column public.members.status is
  '0037: active|past_due|paused|canceled. `paused` = cobro pausado de mutuo acuerdo (pause_collection de Stripe): NO es una baja y conserva los derechos de afiliado.';

-- ============================================================================
-- 4. Los pausados conservan sus derechos
-- ============================================================================
-- Sin esto, pausar la cuota dejaría a la persona sin voto en silencio. Son las
-- tres únicas piezas del esquema que preguntan por una afiliación activa.

create or replace function public.is_active_member(p_user uuid default auth.uid())
returns boolean
language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.members m
    where m.user_id = p_user and m.status in ('active', 'paused')
  );
$$;

comment on function public.is_active_member(uuid) is
  '0037: incluye `paused` — una cuota pausada de mutuo acuerdo no suspende la condición de afiliado (decisión de Sergio). Un impago (past_due) sí queda fuera.';

create or replace function public.is_active_member_since(p_user uuid, p_min_age interval)
returns boolean
language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.members m
    where m.user_id = p_user
      and m.status in ('active', 'paused')
      and m.started_at is not null
      and m.started_at <= now() - p_min_age
  );
$$;

drop view if exists public.budget_scenario_medians;

create view public.budget_scenario_medians
  with (security_invoker = false) as
  select
    m.key::int as ministry_id,
    (exists (
      select 1 from public.members mem
      where mem.user_id = bs.user_id and mem.status in ('active', 'paused')
    )) as is_member,
    percentile_cont(0.5) within group (order by (m.value)::numeric) as median_value,
    count(*) as scenario_count
  from public.budget_scenarios bs,
       jsonb_each_text(bs.allocation) as m(key, value)
  group by 1, 2;

comment on view public.budget_scenario_medians is 'Agregado público "El Presupuesto de la Gente": mediana por ministerio, separando member/público. 0037: un afiliado con la cuota pausada sigue contando como member.';

grant select on public.budget_scenario_medians to anon, authenticated;

commit;
